# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eWrR13p83p0hPnCDo84t1mI8nuXjB9da

# Importing Dataset
"""

# Install required libraries 
!pip install textblob pandas matplotlib

from textblob import TextBlob
import matplotlib.pyplot as plt

#Load the CSV file in drive
from google.colab import files
uploaded = files.upload()

import pandas as pd

# Load CSV File
df = pd.read_csv("StudentWelllness.csv")
df

"""### Checking mood score"""

from textblob import TextBlob

def get_mood_score(text):
    blob = TextBlob(text)
    return round(blob.sentiment.polarity, 2)

!pip install streamlit

import streamlit as st

st.title("Student Mood Analysis")
journal_input = st.text_area("Write your journal entry here:")
if st.button("Analyze"):
    score = get_mood_score(journal_input)
    st.write(f"🧠 Mood Score: {score}")

def burnout_risk(score):
    if score < -0.3:
        return "High Burnout Risk 😟"
    elif score < 0.2:
        return "Moderate Burnout Risk 😐"
    else:
        return "Low Burnout Risk 😄"

if journal_input:
    score = get_mood_score(journal_input)
    risk = burnout_risk(score)
    st.write(f"🔥 Burnout Risk: {risk}")

score = get_mood_score(journal_input)
def wellness_suggestions(score):
    if score < -0.3:
        return ["Talk to a friend or mentor", "Go for a walk", "Try guided meditation", "Do breathing exercises"]
    elif score < 0.2:
        return ["Take small breaks", "Do a fun activity", "Write gratitude journal"]
    else:
        return ["Keep it up!", "Stay connected", "Keep journaling daily","Share your positivity"]

suggestions = wellness_suggestions(score)
st.write("💡 Wellness Suggestions:")
for s in suggestions:
    st.markdown(f"- {s}")

import matplotlib.pyplot as plt

df['mood_score'] = df['journal_text'].apply(get_mood_score)


st.subheader("Mood Score Distribution")
fig, ax = plt.subplots()
df['mood_score'].hist(bins=10, ax=ax)
st.pyplot(fig)

"""## Test with a journal input"""

test_input = "I'm justvery nervous and sad."
score = get_mood_score(test_input)
risk = burnout_risk(score)
suggestions = wellness_suggestions(score)

print("\n📝 Journal Entry:", test_input)
print("🧠 Mood Score:", score)
print("🔥 Burnout Risk:", risk)
print("💡 Wellness Suggestions:")
for s in suggestions:
    print("-", s)
